---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gha-runner.fullname" . }}
  labels:
    {{- include "gha-runner.labels" . | nindent 4 }}
type: Opaque
data:
  github-personal-token: {{ .Values.config.githubPersonalToken | b64enc | quote }}